[package]
name = "chip-8"
version = "0.1.0"
edition = "2021"

[dependencies]
sdl2 = "0.35"
rand = "0.8"
clap = { version = "4.4", features = ["derive"] }
dynasm = "1.2"
dynasmrt = "1.2"
memoffset = "0.6"
